apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 4
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: myapp
        #image: houssemdocker/angular-app:v1 # docker hub image url
        image: jilu407/shruthi-angular-app # local docker image name 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80
    nodePort: 32100 
  type: NodePort 
